"""V-1first revision

Revision ID: dc2ae9a4f6a5
Revises: 
Create Date: 2024-02-22 14:23:01.623716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2ae9a4f6a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fname', sa.String(length=32), nullable=False),
    sa.Column('lname', sa.String(length=32), nullable=False),
    sa.Column('uname', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=70), nullable=False),
    sa.Column('isdeleted', sa.Boolean(), nullable=False),
    sa.Column('iscreated', sa.DateTime(), nullable=True),
    sa.Column('ismodified', sa.DateTime(), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=True),
    sa.Column('isverified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uname')
    )
    op.create_table('otps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=36), nullable=True),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_user_id'), 'otps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otps_user_id'), table_name='otps')
    op.drop_table('otps')
    op.drop_table('users')
    # ### end Alembic commands ###
